version: "3"
services:
    frontend-app:
        build:
            context: ../frontend-app
            dockerfile: Dockerfile
        command: ["/bin/bash", "-c", "nodemon -L /var/www/app/index.js"]
        ports:
            - 48080:8080
        restart: always
